### ISSUE TITLE
Crossplatform capabilities

### ISSUE THREAD

**Issue by Xenthio** [MCT32/2DEngine#2]
NEVER EVER EVER, use windows.h.
A 2d game engine should be based on something cross platform. 
And use makefiles.

**Comment by MCT32** [comment]
I used windows.h since I wanted to use something more low level for once. I'm planing to make an ifdef for Linux and Mac OS but I thought it would be interesting to not use a cross platform library and try do it myself.

**Comment by Xenthio** [comment]
WINDOWS.H ISN'T EVEN THAT LOW LEVEL, SOMETHING MORE CROSSPLATFORM (UNIX LIKE) IS LOWER LEVEL.
